---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "exe/drip"
  - "**.rb"
exclude_paths:
  - "Gemfile.lock"
